<?php

return [

	// Valid names that can be used for search
	'All' => 'All',
	'Apparel' => 'Apparel',
	'Appliances' => 'Appliances',
	'Automotive' => 'Automotive',
	'Baby' => 'Baby',
	'Beauty' => 'Beauty',
	'Blended' => 'Blended',
	'Books' => 'Books',
	'Classical' => 'Classical',
	'DVD' => 'DVD',
	'Electronics' => 'Electronics',
	'Grocery' => 'Grocery',
	'HealthPersonalCare' => 'HealthPersonalCare',
	'HomeGarden' => 'HomeGarden',
	'HomeImprovement' => 'HomeImprovement',
	'Jewelry' => 'Jewelry',
	'KindleStore' => 'KindleStore',
	'Kitchen' => 'Kitchen',
	'Lighting' => 'Lighting',
	'Marketplace' => 'Marketplace',
	'MP3Downloads' => 'MP3Downloads',
	'Music' => 'Music',
	'MusicTracks' => 'MusicTracks',
	'MusicalInstruments' => 'MusicalInstruments',
	'OfficeProducts' => 'OfficeProducts',
	'OutdoorLiving' => 'OutdoorLiving',
	'Outlet' => 'Outlet',
	'PetSupplies' => 'PetSupplies',
	'PCHardware' => 'PCHardware',
	'Shoes' => 'Shoes',
	'Software' => 'Software',
	'SoftwareVideoGames' => 'SoftwareVideoGames',
	'SportingGoods' => 'SportingGoods',
	'Tools' => 'Tools',
	'Toys' => 'Toys',
	'VHS' => 'VHS',
	'Video' => 'Video',
	'VideoGames' => 'VideoGames',
	'Watches' => 'Watches',
];