<?php

return [
	// Locale Reference for the Product Advertising API
	// https://docs.aws.amazon.com/AWSECommerceService/latest/DG/localevalues.html
	// https://docs.aws.amazon.com/AWSECommerceService/latest/DG/LocaleUS.html
	// Default = if do specify BrowseNode = BestSeller
	// Default = if do not specify BrowseNode = Relevance
	// Type = String
	// List Last Updated = 2018-03-11 (yyyy-mm-dd)

	'header' => [
		'Department',
		'Search index',
		'Root Browse node',
		'Sort values',
		'ItemSearch parameters'
	],
	'data' => [
		'All' => [
			'Department' => 'All Departments',
			'SearchIndex' => 'All',
			'RootBrowseNode' => '',
			'SortValues' => [],
			'ItemSearch' => [
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
			],
		],
		'Appliances' => [
			'Department' => 'Appliances',
			'SearchIndex' => 'Appliances',
			'RootBrowseNode' => '2619526011',
			'SortValues' => [
				'salesrank',
				'pmrank',
				'price',
				'-price',
				'relevancerank',
				'reviewrank',
				'reviewrank_authority',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'ArtsAndCrafts' => [
			'Department' => 'Arts, Crafts & Sewing',
			'SearchIndex' => 'ArtsAndCrafts',
			'RootBrowseNode' => '2617942011',
			'SortValues' => [
				'salesrank',
				'pmrank',
				'reviewrank',
				'reviewrank_authority',
				'relevancerank',
				'price',
				'-price',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Automotive' => [
			'Department' => 'Automotive',
			'SearchIndex' => 'Automotive',
			'RootBrowseNode' => '15690151',
			'SortValues' => [
				'salesrank',
				'titlerank',
				'-titlerank',
				'relevancerank',
				'price',
				'-price',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Baby' => [
			'Department' => 'Baby',
			'SearchIndex' => 'Baby',
			'RootBrowseNode' => '165797011',
			'SortValues' => [
				'salesrank',
				'psrank',
				'titlerank',
				'-price',
				'price',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Beauty' => [
			'Department' => 'Beauty',
			'SearchIndex' => 'Beauty',
			'RootBrowseNode' => '11055981',
			'SortValues' => [
				'salesrank',
				'-launch-date',
				'sale-flag',
				'pmrank',
				'price',
				'-price',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Blended' => [
			'Department' => '',
			'SearchIndex' => 'Blended',
			'RootBrowseNode' => '',
			'SortValues' => [],
			'ItemSearch' => [
				'Availability',
				'ItemPage',
				'Keywords'
			],
		],
		'Books' => [
			'Department' => 'Books',
			'SearchIndex' => 'Books',
			'RootBrowseNode' => '1000',
			'SortValues' => [
				'relevancerank',
				'salesrank',
				'reviewrank',
				'pricerank',
				'inverse-pricerank',
				'daterank',
				'titlerank',
				'-titlerank',
				'-unit-sales',
				'price',
				'-price',
				'-publication_date',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPagev',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Power',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'Collectibles' => [
			'Department' => 'Collectibles & Fine Arts',
			'SearchIndex' => 'Collectibles',
			'RootBrowseNode' => '4991426011',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'reviewrank',
				'reviewrank_authority',
				'relevancerank',
			],
			'ItemSearch' => [
				'Artist',
				'Author',
				'Availability',
				'Composer',
				'Conductor',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Orchestra',
				'Sort',
				'Title',
			],
		],
		'Electronics' => [
			'Department' => 'Electronics',
			'SearchIndex' => 'Electronics',
			'RootBrowseNode' => '493964',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'pmrank',
				'reviewrank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Fashion' => [
			'Department' => 'Clothing, Shoes & Jewelry',
			'SearchIndex' => 'Fashion',
			'RootBrowseNode' => '7141124011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'FashionBaby' => [
			'Department' => 'Clothing, Shoes & Jewelry - Baby',
			'SearchIndex' => 'FashionBaby',
			'RootBrowseNode' => '7147444011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'FashionBoys' => [
			'Department' => 'Clothing, Shoes & Jewelry - Boys',
			'SearchIndex' => 'FashionBoys',
			'RootBrowseNode' => '7147443011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'FashionGirls' => [
			'Department' => 'Clothing, Shoes & Jewelry - Girls',
			'SearchIndex' => 'FashionGirls',
			'RootBrowseNode' => '7147442011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'FashionMen' => [
			'Department' => 'Clothing, Shoes & Jewelry - Men',
			'SearchIndex' => 'FashionMen',
			'RootBrowseNode' => '7147441011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'FashionWomen' => [
			'Department' => 'Clothing, Shoes & Jewelry - Women',
			'SearchIndex' => 'FashionWomen',
			'RootBrowseNode' => '7147440011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'GiftCards' => [
			'Department' => 'Gift Cards',
			'SearchIndex' => 'GiftCards',
			'RootBrowseNode' => '2864120011',
			'SortValues' => [
				'relevancerank',
				'salesrank',
				'price',
				'-price',
				'reviewrank_authority',
				'reviewrank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinimumPrice',
				'Neighborhood',
				'Sort',
				'Title',
			],
		],
		'Grocery' => [
			'Department' => 'Grocery & Gourmet Food',
			'SearchIndex' => 'Grocery',
			'RootBrowseNode' => '16310211',
			'SortValues' => [
				'relevancerank',
				'salesrank',
				'pricerank',
				'inverseprice',
				'launch-date',
				'sale-flag',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Handmade' => [
			'Department' => 'Handmade',
			'SearchIndex' => 'Handmade',
			'RootBrowseNode' => '11260433011',
			'SortValues' => [
				'relevancerank',
				'featured',
				'price',
				'-price',
				'reviewrank',
				'-release-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'HealthPersonalCare' => [
			'Department' => 'Health & Personal Care',
			'SearchIndex' => 'HealthPersonalCare',
			'RootBrowseNode' => '3760931',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'pricerank',
				'inverseprice',
				'launch-date',
				'sale-flag',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'HomeGarden' => [
			'Department' => 'Home & Kitchen',
			'SearchIndex' => 'HomeGarden',
			'RootBrowseNode' => '1063498',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Neighborhood',
				'Sort',
				'Title',
			],
		],
		'Industrial' => [
			'Department' => 'Industrial & Scientific',
			'SearchIndex' => 'Industrial',
			'RootBrowseNode' => '16310161',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
			],
			'ItemSearch' => [
				'Availability',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'KindleStore' => [
			'Department' => 'Kindle Store',
			'SearchIndex' => 'KindleStore',
			'RootBrowseNode' => '133141011',
			'SortValues' => [
				'relevancerank',
				'salesrank',
				'-edition-sales-velocity',
				'price',
				'-price',
				'reviewrank',
				'daterank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'LawnAndGarden' => [
			'Department' => 'Patio, Lawn & Garden',
			'SearchIndex' => 'LawnAndGarden',
			'RootBrowseNode' => '3238155011',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'reviewrank',
				'reviewrank_authority',
				'relevancerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Luggage' => [
			'Department' => 'Luggage & Travel Gear',
			'SearchIndex' => 'Luggage',
			'RootBrowseNode' => '9479199011',
			'SortValues' => [
				'relevancerank',
				'popularity-rank',
				'price',
				'-price',
				'reviewrank',
				'launch-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'Condition',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Magazines' => [
			'Department' => 'Magazine Subscriptions',
			'SearchIndex' => 'Magazines',
			'RootBrowseNode' => '599872',
			'SortValues' => [
				'subslot-salesrank',
				'reviewrank',
				'price',
				'-price',
				'daterank',
				'titlerank',
				'-titlerank',
				'-unit-sales',
				'-publication_date',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'Marketplace' => [
			'Department' => '',
			'SearchIndex' => 'Marketplace',
			'RootBrowseNode' => '',
			'SortValues' => [
				'relevancerank',
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
				'-launch-date',
			],
			'ItemSearch' => [],
		],
		'Merchants' => [
			'Department' => '',
			'SearchIndex' => 'Merchants',
			'RootBrowseNode' => '',
			'SortValues' => [
				'relevance',
				'relevancerank',
				'pmrank',
				'price',
				'-price',
				'salesrank',
				'pricerank',
				'inverseprice',
				'launch-date',
				'-launch-date',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'MobileApps' => [
			'Department' => 'Apps & Games',
			'SearchIndex' => 'MobileApps',
			'RootBrowseNode' => '2350150011',
			'SortValues' => [
				'relevancerank',
				'pmrank',
				'price',
				'-price',
				'reviewrank',
				'reviewrank_authority',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Movies' => [
			'Department' => 'Movies & TV',
			'SearchIndex' => 'Movies',
			'RootBrowseNode' => '2625374011',
			'SortValues' => [
				'relevancerank',
				'featured',
				'price',
				'-price',
				'reviewrank',
				'-release-date',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'MP3Downloads' => [
			'Department' => 'Digital Music',
			'SearchIndex' => 'MP3Downloads',
			'RootBrowseNode' => '624868011',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'-releasedate',
				'relevancerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Music' => [
			'Department' => 'CDs & Vinyl',
			'SearchIndex' => 'Music',
			'RootBrowseNode' => '301668',
			'SortValues' => [
				'psrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
				'artistrank',
				'orig-rel-date',
				'-orig-rel-date',
				'release-date',
				'releasedate',
				'-releasedate',
				'relevancerank',
			],
			'ItemSearch' => [
				'Artist',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'MusicalInstruments' => [
			'Department' => 'Musical Instruments',
			'SearchIndex' => 'MusicalInstruments',
			'RootBrowseNode' => '11965861',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'-launch-date',
				'sale-flag',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'OfficeProducts' => [
			'Department' => 'Office Products',
			'SearchIndex' => 'OfficeProducts',
			'RootBrowseNode' => '1084128',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'reviewrank',
				'titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Pantry' => [
			'Department' => 'Prime Pantry',
			'SearchIndex' => 'Pantry',
			'RootBrowseNode' => 'N/A',
			'SortValues' => [
				'relevancerank',
				'price',
				'-price',
				'reviewrank',
			],
			'ItemSearch' => [
				'Availability',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'PCHardware' => [
			'Department' => 'Computers',
			'SearchIndex' => 'PCHardware',
			'RootBrowseNode' => '541966',
			'SortValues' => [
				'psrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'PetSupplies' => [
			'Department' => 'Pet Supplies',
			'SearchIndex' => 'PetSupplies',
			'RootBrowseNode' => '2619534011',
			'SortValues' => [
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
				'relevance',
				'relevancerank',
				'reviewrank',
				'reviewrank_authority',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Software' => [
			'Department' => 'Software',
			'SearchIndex' => 'Software',
			'RootBrowseNode' => '409488',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'SportingGoods' => [
			'Department' => 'Sports & Outdoors',
			'SearchIndex' => 'SportingGoods',
			'RootBrowseNode' => '3375301',
			'SortValues' => [
				'relevancerank',
				'relevance-fs-rank',
				'price',
				'-price',
				'salesrank',
				'pricerank',
				'inverseprice',
				'launch-date',
				'sale-flag',
				'reviewrank_authority',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Tools' => [
			'Department' => 'Tools & Home Improvement',
			'SearchIndex' => 'Tools',
			'RootBrowseNode' => '468240',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Toys' => [
			'Department' => 'Toys & Games',
			'SearchIndex' => 'Toys',
			'RootBrowseNode' => '165795011',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-age-min',
			],
			'ItemSearch' => [
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'UnboxVideo' => [
			'Department' => 'Amazon Instant Video',
			'SearchIndex' => 'UnboxVideo',
			'RootBrowseNode' => '2858778011',
			'SortValues' => [
				'relevancerank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
				'-video-release-date',
				'-launch-date',
			],
			'ItemSearch' => [
				'Actor',
				'AudienceRating',
				'Availability',
				'Director',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'Vehicles' => [
			'Department' => 'Vehicles',
			'SearchIndex' => 'Vehicles',
			'RootBrowseNode' => '10677470011',
			'SortValues' => [
				'relevancerank',
				'featured',
				'reviewrank',
				'-release-date',
			],
			'ItemSearch' => [
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title'
			],
		],
		'VideoGames' => [
			'Department' => 'Video Games',
			'SearchIndex' => 'VideoGames',
			'RootBrowseNode' => '11846801',
			'SortValues' => [
				'pmrank',
				'salesrank',
				'price',
				'-price',
				'titlerank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'Brand',
				'ItemPage',
				'Keywords',
				'Manufacturer',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
		'Wine' => [
			'Department' => 'Wine',
			'SearchIndex' => 'Wine',
			'RootBrowseNode' => '2983386011',
			'SortValues' => [
				'relevancerank',
				'featured',
				'price',
				'-price',
				'reviewrank',
				'reviewscore',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Publisher',
				'Sort',
				'Title',
			],
		],
		'Wireless' => [
			'Department' => 'Cell Phones & Accessories',
			'SearchIndex' => 'Wireless',
			'RootBrowseNode' => '2335753011',
			'SortValues' => [
				'salesrank',
				'pricerank',
				'inverse-pricerank',
				'titlerank',
				'-titlerank',
				'daterank',
				'reviewrank',
			],
			'ItemSearch' => [
				'Author',
				'Availability',
				'ItemPage',
				'Keywords',
				'MaximumPrice',
				'MerchantId',
				'MinPercentageOff',
				'MinimumPrice',
				'Sort',
				'Title',
			],
		],
	]
];